name: WordPress fun!

on:
  push:
    branches:
    - main
  pull_request:
    branches:
    - main

jobs:
  container-job:
    runs-on: ubuntu-20.04
    container:
      image: wordpress:cli

    services:
      mysql:
        image: mysql:5.7
        env:
          MYSQL_ROOT_PASSWORD: riskprofiler
          MYSQL_DATABASE: riskprofiler
        ports:
          - 3306:3306
        options: >-
          --health-cmd "mysqladmin ping"
          --health-interval 10s
          --health-timeout 10s
          --health-retries 10

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Explore
        run: |
          echo -e "[client]\nuser=root\npassword=root" > ~/.my.cnf
          chmod 0600 ~/.my.cnf
          #echo root | mysql_config_editor set --login-path=client --host=localhost --user=root --password
          #mysql_config_editor print --all

      - run: mysql -e "SHOW DATABASES; CREATE DATABASE opendrr; SHOW DATABASES;" || true
      - run: which wp-cli || true
      - run: wp-cli --version || true
      - run: php --version || true

